apiVersion: apps/v1
kind: Deployment
metadata:
  name: instana-autotrace-webhook
  labels:
    {{- include "instana-autotrace-webhook.commonLabels" . | nindent 4 }}
    {{- if .Values.webhook.deployment.additionalLabels }}
    {{ toYaml .Values.webhook.deployment.additionalLabels | indent 4 }}
    {{- end }}
  {{- if .Values.webhook.deployment.additionalAnnotations }}
  annotations:
    {{ toYaml .Values.webhook.deployment.additionalAnnotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.webhook.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: instana-autotrace-webhook
  template:
    metadata:
      name: instana-autotrace-webhook
      labels:
        {{- if .Values.webhook.pod.additionalLabels }}
        {{ toYaml .Values.webhook.pod.additionalLabels | indent 8 }}
        {{- end }}
        {{- include "instana-autotrace-webhook.commonLabels" . | nindent 8 }}
        instana-autotrace-webhook: impl
      {{- if .Values.webhook.pod.additionalAnnotations }}
      annotations:
        {{ toYaml .Values.webhook.pod.additionalAnnotations | indent 8 }}
      {{- end }}
    spec:
      hostNetwork: {{ .Values.webhook.pod.hostNetwork }}
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ .Release.Name }}
      {{- end }}
      securityContext:
      {{- if .Values.webhook.pod.securityContext }}
{{ toYaml .Values.webhook.pod.securityContext | indent 8 }}
      {{- end }}
      imagePullSecrets:
      - name: containers-instana-io
      containers:
      - name: instana-autotrace-webhook
        image: {{ required "You must provide a value for 'webhook.image'" .Values.webhook.image | quote }}
        imagePullPolicy: {{ .Values.webhook.imagePullPolicy }}
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
        env:
        - name: WEBHOOK_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEBHOOK_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVER_PORT
          value: {{ .Values.webhook.pod.port | quote }}
        - name: IGNORED_NAMESPACES
          value: {{ join "," .Values.autotrace.exclude.namespaces }}
        {{- if .Values.autotrace.instrumentation.securityContext }}
        - name: INSTANA_INSTRUMENTATION_INIT_CONTAINER_SECURITY_CONTEXT
          value: {{ toJson .Values.autotrace.instrumentation.securityContext | default "{}" | quote }}
        {{- end }}
        - name: INSTANA_INSTRUMENTATION_INIT_CONTAINER_IMAGE
          value: {{ .Values.autotrace.instrumentation.image | quote }}
        - name: INSTANA_INSTRUMENTATION_INIT_CONTAINER_IMAGE_PULL_POLICY
          value: {{ .Values.autotrace.instrumentation.imagePullPolicy | quote }}
        - name: INSTANA_AUTOTRACE_OPT_IN
          value: {{ .Values.autotrace.opt_in | quote }}
        - name: INSTANA_AUTOTRACE_NODEJS
          value: {{ .Values.autotrace.nodejs.enabled | quote }}
        - name: INSTANA_AUTOTRACE_NETCORE
          value: {{ .Values.autotrace.netcore.enabled | quote }}
        - name: INSTANA_AUTOTRACE_KONG
          value: {{ .Values.autotrace.kong.enabled | quote }}
        - name: INSTANA_AUTOTRACE_INGRESS_NGINX
          value: {{ .Values.autotrace.ingress_nginx.enabled | quote }}
        - name: INSTANA_AUTOTRACE_USE_LIB_INSTANA_INIT
          value: {{ .Values.autotrace.libinstana_init.enabled | quote }}
        {{- if .Values.webhook.debug }}
        - name: LOGGING_LEVEL_ROOT
          value: DEBUG
        {{- end }}
        - name: JAVA_TOOL_OPTIONS
        {{- if (and .Values.webhook.ssl.insecure .Values.webhook.debug) }}
          value: '-Dcom.sun.net.ssl.checkRevocation=false -Djavax.net.debug=ssl,handshake'
        {{- else if .Values.webhook.ssl.insecure }}
          value: '-Dcom.sun.net.ssl.checkRevocation=false'
        {{- else if .Values.webhook.debug }}
          value: '-Djavax.net.debug=all'
        {{- else }}
          value: ''
        {{- end }}
        volumeMounts:
          - name: certificates
            mountPath: /app/certs
        ports:
        - containerPort: {{ .Values.webhook.pod.port }}
      {{- if .Values.webhook.pod.tolerations }}
      tolerations:
        {{- toYaml .Values.webhook.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.webhook.affinity }}
      affinity:
        {{- toYaml .Values.webhook.affinity | nindent 8 }}
      {{- end }}
      volumes:
        - name: certificates
          secret:
            secretName: instana-autotrace-webhook-certs