apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "instana-autotrace-webhook.commonLabels" . | nindent 4 }}
    {{- if .Values.webhook.service.additionalLabels }}
    {{ toYaml .Values.webhook.service.additionalLabels | indent 6 }}
    {{- end }}
  annotations:
    {{- if .Values.webhook.service.additionalAnnotations }}
    {{ toYaml .Values.webhook.service.additionalAnnotations | indent 4 }}
    {{- end }}
spec:
  selector:
    instana-autotrace-webhook: impl
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.pod.port }}