# Default values for instana-autotrace-webhook.

rbac:
  enabled: true # Setting openshift.enabled=true implies rbac.enabled=true
  psp: # Ignored unless rbac.enabled == true
    enabled: true
openshift:
  enabled: false # Deploying on OpenShift implies rbac.enabled=true
webhook:
  debug: false
  ssl:
    insecure: false
    caBundle:
  image: containers.instana.io/instana/release/agent/instana-autotrace-webhook@sha256:673f6e0a31db44784b2ce7e88c8931e323503bf51e6ec53b4a913be6c17aa896
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: containers-instana-io
  imagePullCredentials:
    registry: containers.instana.io
    username: _
    password:
  deployment:
    additionalAnnotations: {}
    additionalLabels: {}
    replicas: 1
  service:
    additionalAnnotations: {}
    additionalLabels: {}
    port: 42650
  pod:
    additionalAnnotations: {}
    additionalLabels: {}
    affinity: {}
    tolerations: []
    port: 42650
    # Ensure that, in case of overlay networks, we bind to the host network, or the control plane
    # won't be able to call into this webhook
    hostNetwork: true # Ignored unless rbac.enabled=true
    # This security context is carried verbatim to the security context of the webhook pod
    securityContext:
    ### Better not to specify CPU resource limits: the WebHook, being a Spring-based app,
    ### needs a burst of CPU on startup, but then is very, very efficient. For more info,
    ### refer to https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-burstable
    resources:
      requests:
        memory: "512Mi"
        #    cpu: 0.5
      limits:
        memory: "1Gi"
        #    cpu: 1.0
autotrace:
  # By default the instana-autotrace-webhook will instrument all pods that are not
  # labelled with `instana-autotrace=false`. If this switch is flipped on,
  # the instana-autotrace-webhook will only touch the pods that have the
  # `instana-autotrace=true` label.
  opt_in: false
  failurePolicy: Ignore # We do not want to cause any trouble in scheduling; for local testing, use 'Fail'
  instrumentation:
    image: instana/instrumentation@sha256:ac807858fb459475e0d91d3426f3567084b306db752ecb1aca992556fe494f96
    imagePullPolicy: IfNotPresent
    # This security context is carried verbatim to the security context of all instrumentation init containers
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all
  kong:
    enabled: true
  ingress_nginx:
    enabled: true
  nodejs:
    enabled: true
  netcore:
    enabled: true
  ruby:
    enabled: true
  libinstana_init:
    enabled: true
  # Namespaces that are always ignored, no matter what
  exclude:
    builtin_namespaces:
      - kube-* # kube-node-lease, kube-public, kube-system
      - instana-* # Avoid conflicts with the Instana Agent and other Instana-related deployments
      - openshift-* # Guess what, Openshift!
      - pks-system # TKGI, formerly known as PKS
    namespaces: []
