# Default values for instana-autotrace-webhook.

rbac:
  enabled: false
webhook:
  debug: false
  ssl:
    insecure: false
    caBundle:
  image: containers.instana.io/instana/release/agent/instana-autotrace-webhook@sha256:4758541fd5d56922d25b0cbebcb50a0a26632b9082d43b8464df2bad3686d0ad
  imagePullPolicy: Always
  imagePullCredentials:
    registry: containers.instana.io
    username: _
    password:
  replicas: 1
autotrace:
  # By default the instana-autotrace-webhook will instrument all pods that are not
  # labelled with `instana-autotrace=false`. If this switch is flipped on,
  # the instana-autotrace-webhook will only touch the pods that have the
  # `instana-autotrace=true` label.
  opt_in: false
  failurePolicy: Ignore # We do not want to cause any trouble in scheduling; for local testing, use 'Fail'
  instrumentation:
    image: instana/instrumentation@sha256:91c6a069ba19dba5416a80d45dda874d0c56a73d23ce3bc543e42a6b8330babd
    imagePullPolicy: Always
  kong:
    enabled: true
  ingress_nginx:
    enabled: true
  nodejs:
    enabled: true
  netcore:
    enabled: true
  libinstana_init:
    enabled: true
  # Namespaces that are always ignored, no matter what
  exclude:
    namespaces:
      - kube-* # kube-node-lease, kube-public, kube-system
      - instana-* # Avoid conflicts with the Instana Agent and other Instana-related deployments
      - openshift-* # Guess what, Openshift!
      - pks-system # TKGI, formerly known as PKS
securityContext:
  enabled: false
  runAsUser: 1001 # If OpenShift, must be in the [1000580000, 1000589999] range
